/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ISR.h"
#include "Clock_3.h"
#include "i2c_scl_aliases.h"
#include "i2c_scl.h"
#include "Button_aliases.h"
#include "Button.h"
#include "EEPROM.h"
#include "UART_RX_IT.h"
#include "Rx_1_aliases.h"
#include "Rx_1.h"
#include "i2c_sda_aliases.h"
#include "i2c_sda.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "LED_aliases.h"
#include "LED.h"
#include "UART.h"
#include "Clock_5.h"
#include "via8bits1_Ctrl.h"
#include "via8bits1_Stat.h"
#include "via8bits1_P0_ctrl.h"
#include "via8bits1_P0_stat.h"
#include "via8bits1_P1_ctrl.h"
#include "via8bits1_P1_stat.h"
#include "via8bits1_gnome_clk.h"
#include "via8bits1_gnome_res.h"
#include "LCD_gnome_A_reg.h"
#include "LCD_gnome_B_reg.h"
#include "UART_IntClock.h"
#include "via8bits2_Ctrl.h"
#include "via8bits2_Stat.h"
#include "via8bits2_P0_ctrl.h"
#include "via8bits2_P0_stat.h"
#include "via8bits2_P1_ctrl.h"
#include "via8bits2_P1_stat.h"
#include "via8bits2_gnome_clk.h"
#include "via8bits2_gnome_res.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

